### ISSUE TITLE
Bengali_News_Classification_Data.csv data availability

### ISSUE THREAD

**Issue by rezacsedu** [goru001/nlp-for-bengali#1]
Thanks for the nice work. I was wondering if the 'Bengali_News_Classification_Data.csv' file is available for download? If size is the issue, a download link would help. 

Thanks.

**Comment by goru001** [comment]
You can checkout the dataset from here: https://www.kaggle.com/csoham/classification-bengali-news-articles-indicnlp

**Comment by rezacsedu** [comment]
@goru001, thanks a million :)
