### ISSUE TITLE
Classification using pretrained TransformerXL model

### ISSUE THREAD

**Issue by susmoy-macgill36** [goru001/nlp-for-bengali#2]
Sir,

Can I apply pretrained TransformerXL instead of ulmfit model for classification? (arch= TransformerXL, and learn.load('model') instead of learn.load('third_bn_lm',with_opt= True)  
(I have already tried, but got less accuracy than ulmfit)

Thank you.

**Comment by goru001** [comment]
@susmoy-macgill36 In general, community hasn't had much success with improving classification performance using TransformerXL architecture as compared to ULMFiT. This [thread](https://forums.fast.ai/t/fastai-transformer-and-transformerxl/38931) might be relevant.

**Comment by susmoy-macgill36** [comment]
Thank you so much, Sir.

**Comment by goru001** [comment]
Thanks. Closing this issue for now. Feel free to reopen if there's anything.
